#!/usr/bin/env python3
"""
deploy_plugins.py - deploy-like flow + test suite for omni-plugins only.

Orchestrates a stack and runs the omni-plugins remote-plugin test suite
(scripts/test_plugins.py in the omni-plugins repo), modeled on deploy.py but
scoped to plugins. Plugins are added to omniagent on the fly as REMOTE
plugins (registered via remote.yml / install-git), so there is no "hybrid"
flavor: dev covers the local-build path, ci covers the image-based path.

Usage:
    python3 deploy_plugins.py dev   # omnidev stack (local omniagent build) + plugin tests
    python3 deploy_plugins.py ci    # stable latest images + plugin tests (no omniagent build)
    python3 deploy_plugins.py test  # just run the plugin test suite (stack must be up)
"""

import argparse
import os
import secrets
import subprocess
import sys
import time

# ═══════════════════════════════════════════════════════════════════════
#  Config
# ═══════════════════════════════════════════════════════════════════════

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WORKSPACE_DIR = os.environ.get("WORKSPACE_DIR", "/opt/workspace")
OMNI_STACK_DIR = os.path.join(WORKSPACE_DIR, "omni-stack")
OMNIAGENT_DIR = os.path.join(WORKSPACE_DIR, "omniagent")
OMNI_PLUGINS_DIR = os.path.join(WORKSPACE_DIR, "omni-plugins")

# Dev mode uses the omnidev stack env file (dev environment ONLY).
OMNIDEV_ENV_PATH = os.path.join(SCRIPT_DIR, "omnidev.env")
# CI mode generates its own env file with the stable `latest` images.
CI_ENV_PATH = os.path.join(SCRIPT_DIR, "plugins-ci.env")

TEST_PLUGINS_SCRIPT = os.path.join(OMNI_PLUGINS_DIR, "scripts", "test_plugins.py")

# Project names: dev = omnidev (the dev stack), ci = omniplugins (a dedicated
# deploy-like project so it never collides with deploy.py's omnideploy).
DEV_PROJECT = "omnidev"
CI_PROJECT = "omniplugins"

# Data volumes that get wiped for a fresh start (like deploy.py). Only volumes
# whose name starts with the CI project prefix are ever deleted.
DATA_VOLUMES = ["postgres_data", "mm-db", "mm-config", "mm-data", "mm-logs", "mm-plugins"]


# ═══════════════════════════════════════════════════════════════════════
#  Helpers
# ═══════════════════════════════════════════════════════════════════════

def sh(cmd):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True)


def compose_cmd(mode):
    cmd = ["docker", "compose", "-f", os.path.join(OMNI_STACK_DIR, "docker-compose.yml")]
    if mode == "dev":
        cmd += ["-f", os.path.join(OMNI_STACK_DIR, "docker-compose.dev.yml")]
    return cmd


def env_path(mode):
    return OMNIDEV_ENV_PATH if mode == "dev" else CI_ENV_PATH


def compose_run(compose, mode, *args):
    """docker compose ... --env-file <env> <args>"""
    return subprocess.run(list(compose) + ["--env-file", env_path(mode)] + list(args),
                          capture_output=True, text=True)


def compose_check(compose, mode, *args, label=""):
    r = compose_run(compose, mode, *args)
    if r.returncode != 0:
        print(r.stdout[-1000:] if r.stdout else "")
        print(r.stderr[-1000:] if r.stderr else "")
        raise RuntimeError(f"{label or 'docker compose'} failed (exit={r.returncode})")
    return r


def wait_for_health(compose, mode, timeout_secs=600):
    """Poll the omniagent /health endpoint until ready."""
    print("[deploy_plugins] Waiting for omniagent health...")
    for i in range(timeout_secs // 2):
        r = compose_run(compose, mode, "exec", "-T", "omniagent",
                        "curl", "-sf", "http://localhost:8080/health")
        if r.returncode == 0:
            print("  omniagent is ready")
            return
        if i % 30 == 0 and i > 0:
            print(f"  still waiting ({i * 2}s)...")
        time.sleep(2)
    raise RuntimeError("omniagent did not become healthy")


def wait_for_db(compose, mode, service, user, db, label="db"):
    for i in range(30):
        r = compose_run(compose, mode, "exec", "-T", service,
                        "pg_isready", "-U", user, "-d", db)
        if r.returncode == 0:
            print(f"  {label} is healthy")
            return
        time.sleep(2)
    raise RuntimeError(f"{label} did not become healthy after 60s")


def generate_ci_env():
    """Generate the CI env file: stable `latest` images, isolated project.

    CI mode does NOT clone/build the omniagent repo - it uses the stable
    images published by deploy.py ci / publish.yml (ghcr.io latest tags).
    """
    p1 = secrets.token_hex(24)
    p2 = secrets.token_hex(24)
    with open(CI_ENV_PATH, "w") as f:
        f.write("# plugins-ci env - generated by deploy_plugins.py (stable latest images)\n")
        f.write(f"COMPOSE_PROJECT_NAME={CI_PROJECT}\n")
        f.write(f"HOST_OMNI_DIR={OMNI_STACK_DIR}\n")
        f.write("COMPOSE_PROFILES=mattermost,noop\n")
        f.write("OMNIAGENT_IMAGE=ghcr.io/nexuslbs/omni-deployer/omniagent:latest\n")
        f.write("DASHBOARD_IMAGE=ghcr.io/nexuslbs/omni-deployer/dashboard:latest\n")
        f.write("TOOLBOX_IMAGE=ghcr.io/nexuslbs/omni-deployer/toolbox:latest\n")
        f.write(f"POSTGRES_PASSWORD={p1}\n")
        f.write(f"MM_POSTGRES_PASSWORD={p2}\n")
        f.write("TUNNEL_TOKEN=\n")
        f.write("BACKUP_CRON_SCHEDULE=\n")
        f.write("CHECKOUT_CRON_SCHEDULE=\n")
    print(f"[deploy_plugins] Generated {CI_ENV_PATH}")


def ensure_omnidev_env():
    """Ensure the omnidev env file exists (normally generated by shared.py).

    If missing, generate it with the same shape shared.generate_env(dev) uses
    (project omnidev, data dir omni-root, noop+mattermost profiles).
    """
    if os.path.exists(OMNIDEV_ENV_PATH):
        return
    p1 = secrets.token_hex(24)
    p2 = secrets.token_hex(24)
    with open(OMNIDEV_ENV_PATH, "w") as f:
        f.write("# omni-dev dev env - generated by deploy_plugins.py\n")
        f.write("COMPOSE_PROJECT_NAME=omnidev\n")
        f.write("HOST_OMNI_DIR=/opt/workspace/omni-root\n")
        f.write("COMPOSE_PROFILES=noop,mattermost\n")
        f.write(f"POSTGRES_PASSWORD={p1}\n")
        f.write(f"MM_POSTGRES_PASSWORD={p2}\n")
        f.write("TUNNEL_TOKEN=\n")
        f.write("BACKUP_CRON_SCHEDULE=\n")
        f.write("CHECKOUT_CRON_SCHEDULE=\n")
    print(f"[deploy_plugins] Generated {OMNIDEV_ENV_PATH}")


def run_plugin_tests(compose, mode, passes=1):
    """Pipe scripts/test_plugins.py into the omniagent container (like tests.py)."""
    if not os.path.exists(TEST_PLUGINS_SCRIPT):
        raise RuntimeError(f"Test script not found: {TEST_PLUGINS_SCRIPT}")
    for pass_num in range(1, passes + 1):
        print(f"\n{'=' * 60}")
        print(f"  PLUGIN TEST SUITE - PASS {pass_num}")
        print(f"{'=' * 60}")
        cmd = list(compose) + ["--env-file", env_path(mode),
                               "exec", "-T", "omniagent", "python3", "-u", "-"]
        print("  Running: docker compose ... exec -T omniagent python3 -u - < test_plugins.py")
        with open(TEST_PLUGINS_SCRIPT, "rb") as f:
            r = subprocess.run(cmd, stdin=f)
        if r.returncode != 0:
            raise RuntimeError(f"Plugin test suite failed (exit={r.returncode})")


# ═══════════════════════════════════════════════════════════════════════
#  Deploy flows
# ═══════════════════════════════════════════════════════════════════════

def _deploy_dev():
    """Dev mode: bring up the omnidev stack with the dev overlay and a local
    omniagent build, then run the plugin test suite.

    Non-destructive: omnidev is the developer's own dev environment, so the
    flow builds the core image from the local repo, ensures services are up,
    runs migrations, and runs the tests. It never tears the stack down.
    """
    ensure_omnidev_env()
    compose = compose_cmd("dev")
    mode = "dev"

    print("\n[deploy_plugins] Building omniagent from local source (dev overlay)...")
    compose_check(compose, mode, "build", "omniagent", label="dev omniagent build")

    print("\n[deploy_plugins] Starting databases...")
    compose_check(compose, mode, "up", "-d", "postgres", "mattermost-db", label="db start")
    wait_for_db(compose, mode, "postgres", "omniagent", "omniagent", "postgres")
    wait_for_db(compose, mode, "mattermost-db", "mmuser", "mattermost", "mattermost-db")

    print("\n[deploy_plugins] Building db-migrations + running migrations...")
    compose_check(compose, mode, "run", "--rm", "omniagent",
                  "cargo", "build", "--release", "-p", "db-migrations",
                  label="build db-migrations")
    compose_check(compose, mode, "run", "--rm", "omniagent",
                  "/target/release/db-migrations", label="migrations")

    print("\n[deploy_plugins] Starting all services...")
    compose_check(compose, mode, "up", "-d", label="services start")
    wait_for_health(compose, mode)

    run_plugin_tests(compose, mode)
    print(f"\n{'=' * 60}")
    print("  ALL PLUGIN TESTS PASSED (dev)")
    print(f"{'=' * 60}")


def _deploy_ci():
    """CI mode: same flow as dev but with the stable `latest` images and NO
    omniagent clone/build. Uses an isolated compose project (omniplugins)."""
    generate_ci_env()
    compose = compose_cmd("ci")
    mode = "ci"

    print("\n[deploy_plugins] Starting databases (stable latest images)...")
    compose_check(compose, mode, "up", "-d", "postgres", "mattermost-db", label="db start")
    wait_for_db(compose, mode, "postgres", "omniagent", "omniagent", "postgres")
    wait_for_db(compose, mode, "mattermost-db", "mmuser", "mattermost", "mattermost-db")

    print("\n[deploy_plugins] Running migrations (db-migrations in image)...")
    compose_check(compose, mode, "run", "--rm", "omniagent", "db-migrations", label="migrations")

    print("\n[deploy_plugins] Starting all services...")
    compose_check(compose, mode, "up", "-d", label="services start")
    wait_for_health(compose, mode)

    run_plugin_tests(compose, mode)
    print(f"\n{'=' * 60}")
    print("  ALL PLUGIN TESTS PASSED (ci)")
    print(f"{'=' * 60}")


def _deploy_test():
    """Just run the plugin test suite against an already-running stack."""
    mode = "dev" if os.path.exists(OMNIDEV_ENV_PATH) else "ci"
    compose = compose_cmd(mode)
    run_plugin_tests(compose, mode)


def main():
    parser = argparse.ArgumentParser(description="OmniPlugins deployer (dev/ci plugin tests)")
    parser.add_argument("mode", choices=["dev", "ci", "test"],
                        help="dev=omnidev stack + local omniagent build, ci=stable latest images, test=run tests only")
    args = parser.parse_args()

    if args.mode == "dev":
        _deploy_dev()
    elif args.mode == "ci":
        _deploy_ci()
    else:
        _deploy_test()


if __name__ == "__main__":
    main()