#!/usr/bin/env python3
"""
Generate an omnidev.env file to run the stable/latest OmniAgent stack in production mode.

Usage:
    python3 omnistable.py

Generates omnidev.env in the script directory, then:
    docker compose -f /path/to/omni-stack/docker-compose.yml --env-file omnidev.env up -d

The env file sets COMPOSE_PROJECT_NAME=omnistable so services are isolated
from other omni deployments, and pins all three main images to their GHCR
stable/latest tags. Profiles are noop,mattermost by default.
"""

import os
import secrets


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_PATH = os.path.join(SCRIPT_DIR, "omnidev.env")


def generate():
    p1 = secrets.token_hex(24)  # POSTGRES_PASSWORD
    p2 = secrets.token_hex(24)  # MM_POSTGRES_PASSWORD

    with open(ENV_PATH, "w") as f:
        f.write("# omni-stable production env\n")
        f.write("# Generated by omnistable.py — use with: docker compose --env-file omnidev.env\n")
        f.write("#\n")
        f.write(f"COMPOSE_PROJECT_NAME=omnistable\n")
        f.write(f"COMPOSE_PROFILES=noop,mattermost\n")
        f.write(f"\n")
        f.write(f"# Main images — GHCR stable/latest tags\n")
        f.write(f"OMNIAGENT_IMAGE=ghcr.io/nexuslbs/omni-deployer/omniagent:latest\n")
        f.write(f"DASHBOARD_IMAGE=ghcr.io/nexuslbs/omni-deployer/dashboard:latest\n")
        f.write(f"TOOLBOX_IMAGE=ghcr.io/nexuslbs/omni-deployer/toolbox:latest\n")
        f.write(f"\n")
        f.write(f"# Database passwords (randomly generated)\n")
        f.write(f"POSTGRES_PASSWORD={p1}\n")
        f.write(f"MM_POSTGRES_PASSWORD={p2}\n")

    print(f"Generated {ENV_PATH}")
    print()
    print("To start the stack:")
    print(f"  docker compose -f /path/to/omni-stack/docker-compose.yml --env-file {ENV_PATH} up -d")
    print()
    print(f"Profiles: noop,mattermost")
    print(f"Project:  omnistable (isolated from other deployments)")
    print(f"Images:")
    print(f"  omniagent:   ghcr.io/nexuslbs/omni-deployer/omniagent:latest")
    print(f"  dashboard:   ghcr.io/nexuslbs/omni-deployer/dashboard:latest")
    print(f"  toolbox:     ghcr.io/nexuslbs/omni-deployer/toolbox:latest")
    print()
    print("⚠️  The passwords in omnidev.env are generated fresh each run.")
    print("   Existing data volumes won't be accessible with new passwords.")


if __name__ == "__main__":
    generate()
