#!/usr/bin/env python3
"""GROUP 54 -- X5 web session/auth recipe for Playwright-MCP (external plan D-2).

Committed regression tests for the recipe delivered by the omnidev task
`task_omnidev_external_plan_x5_web_session_auth` (plan section 7, candidate X5):

  54-A recipe static   the omni-plugins PLUGIN SOURCE (README + mcp-config.json,
                      the deliverable) and the DEPLOYED config both declare a
                      per-site storage-state file, wire --secrets from the
                      secrets store by name and keep state/output in the omni
                      DATA dir (gitignored); the README and the web-interaction
                      skill carry the recipe: login once -> save -> reuse,
                      redact, cookie hygiene, verify after every action, no
                      blind retries.
  54-B storage state   real browser: run 1 logs in and persists storageState;
                      run 2 is a SEPARATE MCP process (a fresh browser) that
                      navigates straight to the account page and is already
                      authenticated -- run 2 contains no login step at all.
  54-C --secrets       a value read from the secrets store, typed into a page,
                      comes back as <secret>NAME</secret> in the tool response
                      and never as the raw value.
  54-D negative        an EMPTY state file does NOT grant access (the account
                      page shows 'Login required'), so 54-B is not vacuous.

The browser fixture site (login -> cookie -> account page) is generated by this
test itself and served on the docker bridge gateway, so the group is offline and
self-contained: no external site, no fixture from the (gitignored) data dir.

The MCP child process is started exactly like servers[0] of the deployed
mcp-config.json, with PW_STATE_FILE / PW_SECRET_* injected the way the plugin
`env:` block does it. No secret value is written to a repo file, to stdout or to
a tool response. The group SKIPs when mcp-playwright is not installed.

Reference: profiles/omni/skills/web-interaction/SKILL.md (recipe),
           profiles/omni/wiki/Reference/Omniagent/Playwright-MCP.md.

Run standalone:  python3 scripts/x5_session_auth.py [--only 54b,54c]
"""

import atexit
import json
import os
import queue
import re
import secrets
import string
import subprocess
import threading
import time
import urllib.error
import urllib.request

OMNI_DIR = os.environ.get("OMNI_DIR") or (
    "/opt/omni" if os.path.isdir("/opt/omni") else "/opt/workspace/omni-stack")
BASE = os.environ.get("OMNI_BASE_URL", "http://localhost:8080")
PLUGIN_DIR = f"{OMNI_DIR}/plugins/tools/.remote/mcp-playwright"
CFG = f"{PLUGIN_DIR}/tools/playwright-mcp/mcp-config.json"
README_DEPLOYED = f"{PLUGIN_DIR}/tools/playwright-mcp/README.md"
# the plugin SOURCE in the omni-plugins checkout (the committed deliverable)
PLUGIN_SRC = os.environ.get(
    "X5_PLUGIN_SRC", "/opt/workspace/omni-plugins/tools/playwright-mcp")
README_SRC = f"{PLUGIN_SRC}/README.md"
CFG_SRC = f"{PLUGIN_SRC}/mcp-config.json"
SKILL = f"{OMNI_DIR}/profiles/omni/skills/web-interaction/SKILL.md"
STATE_DIR = f"{OMNI_DIR}/data/playwright/state"

# self-contained browser fixture (offline): served on the docker bridge gateway
FIXTURE_NAME = "x5-t54-site"
FIXTURE_PORT = int(os.environ.get("X5_T54_PORT", "8117"))
SITE = f"http://host.docker.internal:{FIXTURE_PORT}"
NODE_IMAGE = os.environ.get("X5_T54_IMAGE", "node:22-alpine")
DEMO_USER = "demo-user"
DEMO_PASS = "demo-pass"
SECRET_NAME = "X5_REDACT_TOKEN"

PLACEHOLDER = re.compile(r"\{\{([A-Za-z0-9_]+)\}\}")

WRAPPER_NEEDLES = ("--storage-state=", "PW_STATE_FILE", "/pw/state/", "--isolated",
                   "--secrets=", "PW_SECRET_", "secrets.env", "chmod 700",
                   "chmod 600", "--headless", "--timeout-action=",
                   "--timeout-navigation=", "data/playwright")
README_NEEDLES = ("storage state", "pw_state_file", "--secrets", "<secret>",
                  "cookie hygiene", "login once, then reuse",
                  "browser_run_code_unsafe", "gitignored")
SKILL_NEEDLES = ("PW_STATE_FILE", "--secrets", "<secret>", "storageState",
                 "Cookie hygiene", "Login once, then reuse",
                 "Verify after every action, no blind retries",
                 "never dump cookie values")


def plugin_installed():
    return os.path.exists(CFG)


def skip(msg):
    print(f"SKIP: {msg}")


def _sh(cmd, timeout=120):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True,
                          timeout=timeout)


# ---------------------------------------------------------------------------
# browser fixture: a login page that sets a session cookie -> an account page
# ---------------------------------------------------------------------------
LOGIN_HTML = """<!doctype html><html><head><title>X5 T54 Login</title></head><body>
<h1>T54 demo login</h1>
<form id="f" onsubmit="return go(event)">
<input id="user" name="user" autocomplete="off">
<input id="pass" name="pass" type="password">
<button id="submit" type="submit">Sign in</button>
</form>
<script>
function go(e){e.preventDefault();
  document.cookie="x5_t54_session=ok; path=/";
  location.href="/index.html"; return false;}
</script></body></html>
"""

INDEX_HTML = """<!doctype html><html><head><title>X5 T54 Account</title></head><body>
<h1 id="state"></h1>
<script>
document.getElementById('state').textContent =
  document.cookie.indexOf('x5_t54_session=ok') >= 0
    ? 'Logged In Successfully' : 'Login required';
</script></body></html>
"""

SERVER_JS = """const http=require('http'),fs=require('fs'),p=require('path');
http.createServer((req,res)=>{
  let f=req.url.split('?')[0]; if(f==='/'){f='/index.html';}
  fs.readFile(p.join('/site',f),(e,d)=>{
    if(e){res.writeHead(404);res.end('not found');return;}
    res.writeHead(200,{'Content-Type':'text/html'});res.end(d);});
}).listen(%d,'0.0.0.0');
""" % FIXTURE_PORT


def host_omni():
    """Host path of the omni dir (the fixture is mounted from the host)."""
    cid = open("/etc/hostname", encoding="utf-8").read().strip()
    r = _sh("docker inspect -f '{{range .Mounts}}"
            "{{if eq .Destination \"/opt/omni\"}}{{.Source}}{{end}}{{end}}' " + cid)
    return (r.stdout or "").strip() or None


def fixture_dir():
    h = host_omni()
    if not h:
        return None
    d = f"{h}/data/playwright/{FIXTURE_NAME}"
    os.makedirs(d, exist_ok=True)
    for name, body in (("login.html", LOGIN_HTML), ("index.html", INDEX_HTML),
                       ("server.js", SERVER_JS)):
        with open(f"{d}/{name}", "w", encoding="utf-8") as fh:
            fh.write(body)
    return d


def fixture_up():
    """Start (or reuse) the fixture site on the bridge gateway. Returns bool."""
    d = fixture_dir()
    if not d:
        return False
    _sh("docker rm -f " + FIXTURE_NAME)
    r = _sh(f"docker run -d --name {FIXTURE_NAME} -p 172.17.0.1:{FIXTURE_PORT}:"
            f"{FIXTURE_PORT} -v {d}:/site:ro {NODE_IMAGE} node /site/server.js")
    if r.returncode != 0:
        print(f"  [fixture] docker run failed: {(r.stderr or r.stdout).strip()[:200]}")
        return False
    for _ in range(20):
        c = _sh(f"curl -s -o /dev/null -w '%{{http_code}}' "
                f"http://172.17.0.1:{FIXTURE_PORT}/login.html", timeout=15)
        if (c.stdout or "").strip() == "200":
            return True
        time.sleep(0.5)
    return False


def fixture_down():
    _sh("docker rm -f " + FIXTURE_NAME)
    h = host_omni()
    if h:
        _sh(f"rm -rf {h}/data/playwright/{FIXTURE_NAME}")


atexit.register(lambda: fixture_down())


_FIXTURE_STATE = {}


def ensure_fixture():
    if "ok" not in _FIXTURE_STATE:
        _FIXTURE_STATE["ok"] = fixture_up()
    return _FIXTURE_STATE["ok"]


# ---------------------------------------------------------------------------
# secrets store (values are never printed, logged or written into a repo file)
# ---------------------------------------------------------------------------
def _api(path, data=None, method="GET"):
    req = urllib.request.Request(
        f"{BASE}{path}",
        data=json.dumps(data).encode() if data is not None else None,
        headers={"Content-Type": "application/json"}, method=method)
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.loads(r.read().decode() or "{}")
    except urllib.error.HTTPError as e:
        if e.code in (404, 409):
            return None
        raise


def secret_value(name):
    body = _api(f"/secrets/{name}")
    if not body:
        return None
    return (body.get("data") or {}).get("current_value") or None


def ensure_secret(name):
    val = secret_value(name)
    if val:
        return val
    val = "".join(secrets.choice(string.ascii_letters + string.digits)
                  for _ in range(24))
    _api("/secrets", {"name": name, "fieldType": "password", "value": val}, "POST")
    val = secret_value(name)
    assert val, f"could not create the secret {name} via {BASE}/secrets"
    return val


# ---------------------------------------------------------------------------
# MCP stdio driver (one child process = one browser session)
# ---------------------------------------------------------------------------
def _read_dotenv(path):
    values = {}
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                if v:
                    values[k.strip()] = v
    except FileNotFoundError:
        pass
    return values


class Session:
    """Spawn the deployed mcp-playwright wrapper and speak JSON-RPC on stdio."""

    def __init__(self, env, label):
        self.label = label
        srv = json.load(open(CFG, encoding="utf-8"))["servers"][0]
        child_env = {"PATH": os.environ.get(
            "PATH", "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")}
        child_env.update(env or {})
        self.proc = subprocess.Popen(
            [srv["command"]] + srv["args"], stdin=subprocess.PIPE,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            env=child_env, text=True, bufsize=1)
        self.q = queue.Queue()
        for stream, tag in ((self.proc.stdout, "out"), (self.proc.stderr, "err")):
            threading.Thread(target=self._pump, args=(stream, tag), daemon=True).start()
        self.rid = 1
        self._send({"jsonrpc": "2.0", "id": self.rid, "method": "initialize",
                    "params": {"protocolVersion": "2024-11-05", "capabilities": {},
                               "clientInfo": {"name": "x5-session-auth", "version": "1.0"}}})
        msg, extra = self._wait(self.rid, 180)
        assert msg is not None, f"{label}: MCP initialize failed ({extra[-3:]})"
        self._send({"jsonrpc": "2.0", "method": "notifications/initialized", "params": {}})
        # the wrapper writes the --secrets dotenv before it execs the browser
        self.secret_values = _read_dotenv(f"{STATE_DIR}/secrets.env")

    def _pump(self, stream, tag):
        try:
            for line in stream:
                self.q.put((tag, line))
        except Exception:
            pass

    def _send(self, obj):
        self.proc.stdin.write(json.dumps(obj) + "\n")
        self.proc.stdin.flush()

    def _wait(self, rid, timeout):
        deadline = time.time() + timeout
        extra = []
        while time.time() < deadline:
            try:
                tag, line = self.q.get(timeout=max(0.1, deadline - time.time()))
            except queue.Empty:
                break
            line = line.rstrip("\n")
            if tag == "err":
                extra.append("[stderr] " + line)
                continue
            if not line.strip():
                continue
            try:
                msg = json.loads(line)
            except Exception:
                extra.append("[raw] " + line)
                continue
            if msg.get("id") == rid:
                return msg, extra
            extra.append(line)
        if self.proc.poll() is not None:
            extra.append(f"[wrapper exited rc={self.proc.returncode}]")
        return None, extra

    def call(self, tool, arguments=None, timeout=180):
        self.rid += 1
        self._send({"jsonrpc": "2.0", "id": self.rid, "method": "tools/call",
                    "params": {"name": tool,
                               "arguments": self._substitute(arguments or {})}})
        msg, extra = self._wait(self.rid, timeout)
        assert msg is not None, f"{self.label}: {tool} timed out ({extra[-3:]})"
        result = msg.get("result") or {}
        content = result.get("content") or []
        text = "\n".join(c.get("text", "") for c in content if isinstance(c, dict))
        if not text and msg.get("error"):
            text = json.dumps(msg["error"])
        ok = not msg.get("error") and not result.get("isError")
        return {"tool": tool, "ok": ok, "text": text}

    def _substitute(self, node):
        if isinstance(node, str):
            return PLACEHOLDER.sub(
                lambda m: self.secret_values.get(m.group(1), m.group(0)), node)
        if isinstance(node, list):
            return [self._substitute(x) for x in node]
        if isinstance(node, dict):
            return {k: self._substitute(v) for k, v in node.items()}
        return node

    def close(self):
        try:
            self.proc.stdin.close()
        except Exception:
            pass
        self.proc.terminate()
        try:
            self.proc.wait(timeout=15)
        except Exception:
            self.proc.kill()


def snapshot_text(session):
    snap = session.call("browser_snapshot", {}, 120)
    return snap["text"]


# ---------------------------------------------------------------------------
# 54-A: the recipe is declared in the plugin source/config and documented
# ---------------------------------------------------------------------------
def check_recipe_static():
    if not plugin_installed():
        return skip("mcp-playwright not installed (other stack) - nothing to test")
    # the committed deliverable (omni-plugins source)
    if os.path.exists(CFG_SRC):
        src = open(CFG_SRC, encoding="utf-8").read()
        for needle in WRAPPER_NEEDLES:
            assert needle in src, f"plugin SOURCE mcp-config.json misses {needle!r}"
    if os.path.exists(README_SRC):
        rd = open(README_SRC, encoding="utf-8").read().lower()
        for needle in README_NEEDLES:
            assert needle in rd, \
                f"plugin SOURCE README misses the X5 recipe statement {needle!r}"
    # the config that is actually deployed (also carries the $secret: env ref)
    cfg = open(CFG, encoding="utf-8").read()
    for needle in WRAPPER_NEEDLES + ("$secret:",):
        assert needle in cfg, f"deployed wrapper config misses {needle!r}"
    # The profile skill that documents the recipe is a hand-authored profile
    # file: another setup may legitimately not ship it. Assert its content when
    # it is present (a shipped skill that lost the recipe is still a failure)
    # and SKIP instead of failing on the fixed path when it is absent, so the
    # group stays setup-agnostic (no hard dependency on a profiles/... fixture
    # existing). The skill LOAD path is asserted behaviourally elsewhere
    # (tests.py group 45-A seeds a skill and asserts the skills tool loads it).
    if os.path.exists(SKILL):
        sk = open(SKILL, encoding="utf-8").read()
        for needle in SKILL_NEEDLES:
            assert needle in sk, \
                f"web-interaction skill misses the X5 recipe statement {needle!r}"
        skill_note = "the web-interaction skill carries it too"
    else:
        skip(f"profile skill {SKILL} is absent in this setup (setup-agnostic) - "
             "the skill content assertions are skipped")
        skill_note = (f"the web-interaction skill is absent in this setup "
                      f"({SKILL}) - content check skipped")
    assert os.path.isdir(STATE_DIR), f"state dir missing: {STATE_DIR}"
    gi = f"{OMNI_DIR}/.gitignore"
    gi_txt = open(gi, encoding="utf-8").read() if os.path.exists(gi) else ""
    assert re.search(r"(?m)^/?data/?\s*$", gi_txt), \
        "the omni dir does not gitignore the data/ dir holding the state files"
    print("PASS: 54-A plugin source + deployed wrapper declare per-site "
          "--storage-state and --secrets (secrets by name), state lives under the "
          "gitignored data dir; the README carries the "
          "login-once/reuse/redact/cookie-hygiene/no-blind-retry recipe; "
          f"{skill_note}")


# ---------------------------------------------------------------------------
# 54-B: login once, save the storage state, reuse it in a NEW process
# ---------------------------------------------------------------------------
def check_storage_state_roundtrip():
    if not plugin_installed():
        return skip("mcp-playwright not installed (other stack) - nothing to test")
    if not ensure_fixture():
        raise AssertionError("could not start the self-contained browser fixture site")
    state = "x5-t54-roundtrip.json"
    path = f"{STATE_DIR}/{state}"
    if os.path.exists(path):
        os.remove(path)
    s1 = Session({"PW_STATE_FILE": state}, "54-B run1")
    try:
        nav = s1.call("browser_navigate", {"url": f"{SITE}/login.html"}, 180)
        assert nav["ok"], f"run1 navigate failed: {nav['text'][:300]}"
        s1.call("browser_type", {"target": "#user", "text": DEMO_USER}, 120)
        s1.call("browser_type", {"target": "#pass", "text": DEMO_PASS}, 120)
        click = s1.call("browser_click", {"target": "#submit"}, 180)
        assert click["ok"], f"run1 login click failed: {click['text'][:300]}"
        body = snapshot_text(s1).lower()
        assert "logged in successfully" in body, \
            f"run1 login did not reach the account page: {body[:300]}"
        save = s1.call("browser_run_code_unsafe", {"code": (
            "async (page) => { await page.context().storageState("
            f"{{ path: '/pw/state/{state}' }}); return 'storage state saved'; }}" )}, 120)
        assert save["ok"], f"saving the storage state failed: {save['text'][:300]}"
        assert state in save["text"] or "storage state saved" in save["text"], \
            f"unexpected save result: {save['text'][:200]}"
        s1.call("browser_close", {}, 60)
    finally:
        s1.close()

    assert os.path.exists(path), f"run1 did not write the per-site state file {path}"
    blob = open(path, encoding="utf-8").read()
    assert "cookies" in blob and "host.docker.internal" in blob, \
        f"the saved state has no cookies for the site: {blob[:200]}"

    s2 = Session({"PW_STATE_FILE": state}, "54-B run2")
    try:
        nav2 = s2.call("browser_navigate", {"url": f"{SITE}/index.html"}, 180)
        assert nav2["ok"], f"run2 navigate failed: {nav2['text'][:300]}"
        body2 = snapshot_text(s2).lower()
        assert "logged in successfully" in body2, \
            f"run2 (no login step) is not authenticated - state not reused: {body2[:300]}"
        assert "login required" not in body2, \
            f"run2 showed the anonymous page although a state file was supplied: {body2[:300]}"
    finally:
        s2.close()
    print(f"PASS: 54-B login once -> {state} saved (session cookie for the site) -> a "
          "FRESH MCP process with the same PW_STATE_FILE landed on the account page "
          "with no login step at all (session reused, not re-authenticated)")


# ---------------------------------------------------------------------------
# 54-C: --secrets redaction keeps the raw value out of every tool response
# ---------------------------------------------------------------------------
def check_secrets_redaction():
    if not plugin_installed():
        return skip("mcp-playwright not installed (other stack) - nothing to test")
    if not ensure_fixture():
        raise AssertionError("could not start the self-contained browser fixture site")
    val = ensure_secret(SECRET_NAME)
    s = Session({"PW_STATE_FILE": "x5-t54-redact.json",
                 "PW_SECRET_" + SECRET_NAME: val}, "54-C")
    try:
        assert s.call("browser_navigate", {"url": f"{SITE}/login.html"}, 180)["ok"]
        res = s.call("browser_type", {"target": "#user", "text": val}, 120)
        assert res["ok"], f"type with the secret value failed: {res['text'][:300]}"
        assert val not in res["text"], \
            "RAW secret value leaked into the tool response (redaction broken)"
        assert f"<secret>{SECRET_NAME}</secret>" in res["text"], \
            f"the value was not replaced by the redaction placeholder: {res['text'][:300]}"
    finally:
        s.close()
    envf = f"{STATE_DIR}/secrets.env"
    assert os.path.exists(envf), "the wrapper did not write the --secrets dotenv"
    mode = oct(os.stat(envf).st_mode & 0o777)
    assert mode in ("0o600", "0o640", "0o644"), f"secrets.env mode {mode} is too open"
    for p in (CFG, README_DEPLOYED, README_SRC, CFG_SRC, SKILL):
        if os.path.exists(p):
            assert val not in open(p, encoding="utf-8").read(), \
                f"the secret value is present in {p} (must stay in the store only)"
    print(f"PASS: 54-C --secrets redaction: the value from the secrets store came back "
          f"as <secret>{SECRET_NAME}</secret> in the tool response, never raw; "
          f"secrets.env {mode} under the gitignored state dir; no literal in "
          "config/README/skill")


# ---------------------------------------------------------------------------
# 54-D: negative control -- an empty state file grants nothing
# ---------------------------------------------------------------------------
def check_negative_control():
    if not plugin_installed():
        return skip("mcp-playwright not installed (other stack) - nothing to test")
    if not ensure_fixture():
        raise AssertionError("could not start the self-contained browser fixture site")
    state = "x5-t54-empty.json"
    path = f"{STATE_DIR}/{state}"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write('{"cookies":[],"origins":[]}')
    s = Session({"PW_STATE_FILE": state}, "54-D")
    try:
        nav = s.call("browser_navigate", {"url": f"{SITE}/index.html"}, 180)
        assert nav["ok"], f"navigate failed: {nav['text'][:300]}"
        body = snapshot_text(s).lower()
        assert "login required" in body, \
            f"expected the anonymous page with an empty state file: {body[:300]}"
        assert "logged in successfully" not in body, \
            "an EMPTY state file granted access - 54-B would be vacuous"
    finally:
        s.close()
    st = os.stat(path)
    if st.st_uid == 1000:
        assert oct(st.st_mode & 0o777) == "0o600", \
            f"state file mode {oct(st.st_mode & 0o777)} (wrapper keeps 700/600)"
    print("PASS: 54-D empty state file -> the account page shows 'Login required' "
          "(access comes from the saved session, not from the browser being open)")


CHECKS = {
    "54a": check_recipe_static,
    "54b": check_storage_state_roundtrip,
    "54c": check_secrets_redaction,
    "54d": check_negative_control,
}


def main(argv):
    only = None
    if "--only" in argv:
        only = set(argv[argv.index("--only") + 1].split(","))
    failed = 0
    for key, fn in CHECKS.items():
        if only and key not in only:
            continue
        try:
            fn()
        except AssertionError as e:
            print(f"FAIL: {key}: {e}")
            failed += 1
        except Exception as e:  # noqa: BLE001 - the runner turns it into a failed test
            print(f"FAIL: {key}: {type(e).__name__}: {e}")
            failed += 1
    print(json.dumps({"group": 54, "failed": failed}))
    return 1 if failed else 0


if __name__ == "__main__":
    sys_exit = main([a for a in os.sys.argv[1:]])
    fixture_down()
    raise SystemExit(sys_exit)
